import type { UiCopyCatalog } from "../lib/ui-localization.js";

/**
 * Static, authored copy exposed by web/editor.html and editor.css.
 *
 * Korean source copy is deliberately used as the stable lookup key so the
 * authored HTML remains the no-JavaScript fallback. Runtime-generated copy
 * belongs in a separate catalog with typed interpolation patterns.
 */
export const EDITOR_STATIC_UI_COPY = {
  "Kirinuki 영상 편집기": { en: "Kirinuki Video Editor", ja: "Kirinuki 動画エディター" },
  "이 주소에서는 편집기를 열 수 없습니다": { en: "The editor cannot be opened from this address", ja: "このアドレスからエディターを開くことはできません" },
  "정식 Kirinuki 웹사이트에서 다시 시작해 주세요.": { en: "Start again from the official Kirinuki website.", ja: "Kirinuki 公式サイトからやり直してください。" },
  "Kirinuki로 이동": { en: "Go to Kirinuki", ja: "Kirinuki へ移動" },
  "편집기는 모바일에서 사용할 수 없습니다": { en: "The editor is not available on mobile", ja: "モバイルではエディターを利用できません" },
  "영상 편집과 내보내기는 키보드와 정밀 포인터를 사용할 수 있는 PC 브라우저에서 진행해 주세요.": { en: "Edit and export video in a desktop browser with a keyboard and precision pointer.", ja: "動画の編集と書き出しは、キーボードと精密なポインターを使用できるPCブラウザーで行ってください。" },
  "시작 화면으로 돌아가기": { en: "Return to Start", ja: "スタート画面に戻る" },
  "편집 영상 준비": { en: "Prepare Media", ja: "編集用メディアを準備" },
  "내 파일 직접 연결": { en: "Choose Local File", ja: "ローカルファイルを選択" },
  "본편 편집으로": { en: "Back to Main Edit", ja: "本編編集に戻る" },
  "쇼츠 편집기": { en: "Shorts Editor", ja: "ショート動画編集" },
  "영상 내보내기": { en: "Export", ja: "書き出し" },
  "지금 저장": { en: "Save Version", ja: "バージョンを保存" },
  "저장·복구본": { en: "Versions & Recovery", ja: "保存版・復元" },
  "편집 중 임시 복구 · 탭 종료 시 폐기": { en: "Temporary edit recovery · Discarded when this tab closes", ja: "編集中の一時復元 · タブを閉じると破棄" },
  "작업 끝내기": { en: "Finish Editing", ja: "編集を終了" },
  "선택한 구간": { en: "Selected Clips", ja: "選択クリップ" },
  "본편 컷 재생 순서입니다. 위에서 아래 순서로 이어서 재생되며, 범위는 자동으로 늘어나거나 줄어들지 않습니다.": { en: "This is the playback order for the main edit. Clips play from top to bottom, and their ranges do not expand or shrink automatically.", ja: "本編クリップの再生順です。上から下へ順に再生され、範囲が自動で伸縮することはありません。" },
  "편집 영상 준비 전": { en: "Media Not Prepared", ja: "編集用メディア未準備" },
  "선택한 구간에 필요한 영상만 이 기기에 가져옵니다": { en: "Only the media required for the selected clips is downloaded to this device", ja: "選択クリップに必要な映像だけをこのデバイスに取得します" },
  "페이지 시각 ↔ 이 기기의 원본 정렬": { en: "Page Time ↔ Local Source Sync", ja: "ページ時刻 ↔ ローカル素材の同期" },
  "초": { en: "sec", ja: "秒" },
  "적용": { en: "Apply", ja: "適用" },
  "이 기기 원본 시각 = 페이지에서 찍은 시각 + 차이값": { en: "Local source time = time marked on the page + offset", ja: "ローカル素材時刻 = ページで記録した時刻 + オフセット" },
  "체크한 컷 없음": { en: "No clips selected", ja: "選択中のクリップはありません" },
  "해제": { en: "Clear", ja: "解除" },
  "원래 영상 탭으로 돌아가기": { en: "Return to Source Video Tab", ja: "元の動画タブに戻る" },
  "편집 미리보기": { en: "Program Monitor", ja: "プログラムモニター" },
  "원본 시각으로 이동": { en: "Go to Source Timecode", ja: "ソースタイムコードへ" },
  "쇼츠에 영상 추가": { en: "Add Video to Shorts", ja: "ショート動画に映像を追加" },
  "에이전트로 자막 넣기": { en: "Add Captions with an Agent", ja: "エージェントで字幕を追加" },
  "드래그해서 가져올 화면 선택": { en: "Drag to select the source area", ja: "ドラッグして取り込む範囲を選択" },
  "쇼츠로 가져올 구간과 화면": { en: "Clip Range & Source Area", ja: "取り込む範囲と画面領域" },
  "본편의 시간 범위와 원본 화면 영역만 골라 보냅니다. 본편 컷은 바뀌지 않습니다.": { en: "Choose only a time range and source area from the main edit. The main edit remains unchanged.", ja: "本編から時間範囲と元映像の領域だけを選びます。本編のクリップは変更されません。" },
  "현재 쇼츠 화면에 영상 추가": { en: "Add Video to the Current Shorts Canvas", ja: "現在のショート画面に映像を追加" },
  "지금 고르는 구간은 기존 영상과 별개로 현재 재생 시각부터 배치됩니다.": { en: "This range is placed at the current playhead, independently of existing video.", ja: "選択した範囲は既存の映像とは別に、現在の再生ヘッド位置から配置されます。" },
  "새 장면으로 만들기": { en: "Create as New Scene", ja: "新しいシーンとして作成" },
  "1. 가져올 시간": { en: "1. Time Range", ja: "1. 取り込む時間" },
  "현재 컷 전체": { en: "Entire Current Clip", ja: "現在のクリップ全体" },
  "이 컷의 끝까지 가져오기": { en: "Through End of This Clip", ja: "このクリップの末尾まで" },
  "시작": { en: "Start", ja: "開始" },
  "시작 보기": { en: "Preview Start", ja: "開始位置を確認" },
  "−1초": { en: "−1 sec", ja: "−1秒" },
  "−0.1초": { en: "−0.1 sec", ja: "−0.1秒" },
  "현재 위치": { en: "Playhead", ja: "再生ヘッド" },
  "+0.1초": { en: "+0.1 sec", ja: "+0.1秒" },
  "+1초": { en: "+1 sec", ja: "+1秒" },
  "이 시작점의 컷 시작": { en: "Start of This Clip", ja: "このクリップの先頭" },
  "끝": { en: "End", ja: "終了" },
  "끝 직전 보기": { en: "Preview End Frame", ja: "終了直前を確認" },
  "이 끝점의 컷 끝": { en: "End of This Clip", ja: "このクリップの末尾" },
  "시각 입력에서 ↑/↓는 0.1초, Shift+↑/↓는 1초 이동합니다. ‘보기’로 실제 경계 프레임을 확인하고 타임라인의 보라색 손잡이로도 조절할 수 있습니다.": { en: "In a time field, ↑/↓ moves by 0.1 sec and Shift+↑/↓ by 1 sec. Use Preview to check the actual boundary frame, or adjust the purple timeline handles.", ja: "時刻欄では↑/↓で0.1秒、Shift+↑/↓で1秒移動します。プレビューで実際の境界フレームを確認するか、タイムラインの紫色のハンドルでも調整できます。" },
  "2. 원본에서 가져올 화면": { en: "2. Source Area", ja: "2. 元映像から取り込む領域" },
  "너비": { en: "Width", ja: "幅" },
  "높이": { en: "Height", ja: "高さ" },
  "자유": { en: "Freeform", ja: "自由" },
  "원본 전체": { en: "Full Source", ja: "元映像全体" },
  "선택 영역과 손잡이에 포커스한 뒤 방향키로 1픽셀, Shift+방향키로 10픽셀씩 조절할 수 있습니다.": { en: "Focus the selection or a handle, then use the arrow keys to adjust by 1 px, or Shift+arrow keys by 10 px.", ja: "選択領域またはハンドルにフォーカスし、矢印キーで1px、Shift+矢印キーで10pxずつ調整できます。" },
  "시간 00:00.000–00:03.000 · 화면 준비 중": { en: "Time 00:00.000–00:03.000 · Preparing preview", ja: "時間 00:00.000–00:03.000 · プレビューを準備中" },
  "취소": { en: "Cancel", ja: "キャンセル" },
  "쇼츠에 추가만": { en: "Add to Shorts", ja: "ショート動画に追加" },
  "추가하고 쇼츠에서 배치": { en: "Add & Position in Shorts", ja: "追加してショート画面に配置" },
  "이동": { en: "Move", ja: "移動" },
  "편집할 영상을 준비해 주세요": { en: "Prepare media to start editing", ja: "編集するメディアを準備してください" },
  "선택한 구간을 기준으로 필요한 영상만 이 기기에 가져옵니다. 부족한 앞뒤 구간은 편집 중 더 준비할 수 있습니다": { en: "Only media needed for the selected clips is downloaded to this device. You can fetch more before or after them while editing.", ja: "選択クリップに必要な映像だけをこのデバイスに取得します。前後に足りない範囲は編集中に追加できます。" },
  "자막": { en: "Captions", ja: "字幕" },
  "이미지": { en: "Image", ja: "画像" },
  "음성": { en: "Audio", ja: "オーディオ" },
  "영상": { en: "Video", ja: "映像" },
  "한글 자막": { en: "Korean Captions", ja: "韓国語字幕" },
  "+ 직접 추가": { en: "+ Add Manually", ja: "+ 手動で追加" },
  "자막 위치 자동으로 넣기": { en: "Auto-place Captions", ja: "字幕位置を自動配置" },
  "자막 위치를 찾는 중": { en: "Finding caption positions", ja: "字幕位置を検索中" },
  "완성본 기준 · Pretendard 클린": { en: "Delivery Default · Pretendard Clean", ja: "完成版基準 · Pretendard クリーン" },
  "흰 자막 · 검은 사각 배경": { en: "White Captions · Black Box", ja: "白字幕 · 黒いボックス" },
  "OFL 대안 · Paperlogy 클린": { en: "OFL Alternative · Paperlogy Clean", ja: "OFL代替 · Paperlogy クリーン" },
  "기존 프로젝트 사용자 설정": { en: "Existing Project Settings", ja: "既存プロジェクトの設定" },
  "소리가 있는 구간의 빈 자막 위치를 찾습니다.": { en: "Finds open caption positions in segments with audio.", ja: "音声がある区間で空いている字幕位置を探します。" },
  "준비됨": { en: "Ready", ja: "準備完了" },
  "Whisper 확인": { en: "Check Whisper", ja: "Whisperを確認" },
  "사용하지 않음": { en: "Off", ja: "使用しない" },
  "연결된 모델 없음": { en: "No Model Connected", ja: "接続済みモデルなし" },
  "Whisper 모델": { en: "Whisper Model", ja: "Whisperモデル" },
  "Whisper 개발 기능": { en: "Whisper Experimental Features", ja: "Whisper開発機能" },
  "자동 위치 초기화": { en: "Reset Auto-placement", ja: "自動配置をリセット" },
  "자막 스타일 비교": { en: "Compare Caption Styles", ja: "字幕スタイルを比較" },
  "자막 문구는 표시하지 않고 위치·크기·색상·검은 상자 설정을 시간순으로 비교합니다.": { en: "Compare position, size, color, and black-box settings in timeline order without showing caption text.", ja: "字幕テキストを表示せず、位置・サイズ・色・黒いボックスの設定を時系列で比較します。" },
  "스타일 비교 열기": { en: "Open Style Comparison", ja: "スタイル比較を開く" },
  "선택 자막": { en: "Selected Caption", ja: "選択中の字幕" },
  "전체": { en: "All", ja: "すべて" },
  "자막을 선택해 주세요": { en: "Select a caption", ja: "字幕を選択してください" },
  "타임라인의 자막 블록을 누르면 텍스트와 위치를 수정할 수 있습니다.": { en: "Select a caption block on the timeline to edit its text and position.", ja: "タイムラインの字幕ブロックを選択すると、テキストと位置を編集できます。" },
  "AI 재확인 필요": { en: "AI Review Required", ja: "AI要確認" },
  "불명확한 발화로 표시된 자막입니다. 원음을 듣고 텍스트를 한 번 확인해 주세요.": { en: "This caption contains uncertain speech. Listen to the source audio and review the text.", ja: "不明瞭な発話として検出された字幕です。元の音声を聞いてテキストを確認してください。" },
  "자막 텍스트": { en: "Caption Text", ja: "字幕テキスト" },
  "아래 타임라인 양끝 손잡이로도 조정할 수 있어요.": { en: "You can also adjust it with the handles at either end of the timeline block.", ja: "下のタイムラインブロック両端のハンドルでも調整できます。" },
  "선택 이미지 구간에 정확히 맞춤": { en: "Match Selected Image Range", ja: "選択画像の範囲に合わせる" },
  "같은 컷의 이미지를 선택하면 양끝 시각을 한 번에 맞출 수 있어요.": { en: "Select an image in the same clip to match both boundaries at once.", ja: "同じクリップの画像を選ぶと、開始・終了時刻を一度に合わせられます。" },
  "이 자막 검은 상자 켜기 · X": { en: "Toggle Black Box for This Caption · X", ja: "この字幕の黒いボックスを切り替え · X" },
  "← 왼쪽 자막 · J": { en: "← Previous Caption · J", ja: "← 前の字幕 · J" },
  "오른쪽 자막 · K →": { en: "Next Caption · K →", ja: "次の字幕 · K →" },
  "화면 위치": { en: "Position", ja: "画面位置" },
  "영상 위 자막을 직접 끌어서 원하는 곳에 놓을 수 있습니다.": { en: "Drag the caption directly on the video to position it.", ja: "映像上の字幕を直接ドラッグして配置できます。" },
  "가로": { en: "X", ja: "横" },
  "세로": { en: "Y", ja: "縦" },
  "스타일": { en: "Style", ja: "スタイル" },
  "선택 자막 크기": { en: "Selected Caption Size", ja: "選択字幕のサイズ" },
  "선택 자막 색상": { en: "Selected Caption Color", ja: "選択字幕の色" },
  "기본 흰색으로": { en: "Reset to White", ja: "白に戻す" },
  "이 자막 삭제": { en: "Delete This Caption", ja: "この字幕を削除" },
  "클립보드 이미지 붙여넣기": { en: "Paste Image from Clipboard", ja: "クリップボードから画像を貼り付け" },
  "이미지 파일 선택": { en: "Choose Image File", ja: "画像ファイルを選択" },
  "웹에서 ‘이미지 복사’ 후 Ctrl/Cmd+V를 눌러도 됩니다. PNG·WebP의 투명 배경은 그대로 유지됩니다.": { en: "You can also copy an image on the web and press Ctrl/Cmd+V. Transparency in PNG and WebP files is preserved.", ja: "Web上で画像をコピーしてCtrl/Cmd+Vで貼り付けることもできます。PNG・WebPの透明部分は保持されます。" },
  "이미지를 추가해 주세요": { en: "Add an image", ja: "画像を追加してください" },
  "붙여넣은 이미지는 현재 재생 위치부터 영상 위에 표시됩니다.": { en: "A pasted image appears over the video from the current playhead.", ja: "貼り付けた画像は現在の再生ヘッド位置から映像上に表示されます。" },
  "투명 이미지 지원": { en: "Transparency Supported", ja: "透過画像対応" },
  "이미지 트랙 양끝 손잡이로도 표시 시간을 조정할 수 있어요.": { en: "You can also adjust its duration with the handles at either end of the image track.", ja: "画像トラック両端のハンドルでも表示時間を調整できます。" },
  "선택 자막 구간에 정확히 맞춤": { en: "Match Selected Caption Range", ja: "選択字幕の範囲に合わせる" },
  "같은 컷의 자막을 선택하면 양끝 시각을 한 번에 맞출 수 있어요.": { en: "Select a caption in the same clip to match both boundaries at once.", ja: "同じクリップの字幕を選ぶと、開始・終了時刻を一度に合わせられます。" },
  "영상 위 이미지를 직접 끌어서 위치를 바꿀 수도 있습니다.": { en: "You can also drag the image directly on the video to reposition it.", ja: "映像上の画像を直接ドラッグして位置を変更することもできます。" },
  "크기": { en: "Size", ja: "サイズ" },
  "불투명도": { en: "Opacity", ja: "不透明度" },
  "이 이미지 삭제": { en: "Delete This Image", ja: "この画像を削除" },
  "음성 구간을 선택해 주세요": { en: "Select an audio segment", ja: "オーディオ区間を選択してください" },
  "음성 트랙의 기본 블록을 누르거나 우클릭해 조절 구간을 만들 수 있습니다.": { en: "Select the base block on the audio track, or right-click to create an adjustment segment.", ja: "オーディオトラックの基本ブロックを選択するか、右クリックして調整区間を作成できます。" },
  "선택 구간 음성": { en: "Selected Segment Audio", ja: "選択区間のオーディオ" },
  "구간 음량": { en: "Segment Volume", ja: "区間音量" },
  "이 구간 음소거": { en: "Mute This Segment", ja: "この区間をミュート" },
  "페이드 인": { en: "Fade In", ja: "フェードイン" },
  "0.0초": { en: "0.0 sec", ja: "0.0秒" },
  "페이드 아웃": { en: "Fade Out", ja: "フェードアウト" },
  "음성 설정 초기화": { en: "Reset Audio Settings", ja: "オーディオ設定をリセット" },
  "이 음성 설정 구간 삭제": { en: "Delete This Audio Segment", ja: "このオーディオ設定区間を削除" },
  "독립 저장": { en: "Saved Separately", ja: "個別保存" },
  "쇼츠 작업": { en: "Shorts Projects", ja: "ショート動画プロジェクト" },
  "현재 작업": { en: "Current Project", ja: "現在のプロジェクト" },
  "작업 이름": { en: "Project Name", ja: "プロジェクト名" },
  "각 작업의 자막·영상·실행 취소·내보내기는 서로 섞이지 않습니다.": { en: "Captions, video, undo history, and exports are kept separate for each project.", ja: "字幕・映像・取り消し履歴・書き出しはプロジェクトごとに分けて管理されます。" },
  "+ 새 작업": { en: "+ New Project", ja: "+ 新規プロジェクト" },
  "복제": { en: "Duplicate", ja: "複製" },
  "삭제": { en: "Delete", ja: "削除" },
  "선택 영상": { en: "Selected Video", ja: "選択中の映像" },
  "쇼츠 화면에서 편집할 영상을 선택해 주세요.": { en: "Select a video to edit on the Shorts canvas.", ja: "ショート画面で編集する映像を選択してください。" },
  "원본 구간과 길이가 여기에 표시됩니다.": { en: "Its source range and duration appear here.", ja: "元の範囲と長さがここに表示されます。" },
  "영상 목록": { en: "Video List", ja: "映像一覧" },
  "+ 영상 추가": { en: "+ Add Video", ja: "+ 映像を追加" },
  "영상을 선택하면 아래에서 구간·표시·불투명도·소리를 편집할 수 있습니다.": { en: "Select a video to edit its range, visibility, opacity, and audio below.", ja: "映像を選択すると、下で範囲・表示・不透明度・音声を編集できます。" },
  "이 기기에서 영상 미리보기를 준비합니다.": { en: "Preparing the video preview on this device.", ja: "このデバイスで映像プレビューを準備します。" },
  "미리보기 다시 만들기": { en: "Rebuild Preview", ja: "プレビューを再作成" },
  "현재 쇼츠 화면이 비어 있습니다. ‘영상 추가’로 본편 구간을 가져오세요.": { en: "The Shorts canvas is empty. Use Add Video to bring in a range from the main edit.", ja: "ショート画面は空です。「映像を追加」で本編の範囲を取り込んでください。" },
  "쇼츠 시작": { en: "Shorts In", ja: "ショート開始" },
  "쇼츠 끝": { en: "Shorts Out", ja: "ショート終了" },
  "영상 음량": { en: "Video Volume", ja: "映像の音量" },
  "원본 음량은 100%입니다. 100%를 넘기면 큰 소리가 찌그러질 수 있습니다.": { en: "The source level is 100%. Levels above 100% may distort loud audio.", ja: "元の音量は100%です。100%を超えると大きな音が歪む場合があります。" },
  "표시 중": { en: "Visible", ja: "表示中" },
  "선택 영상 배치 · 픽셀": { en: "Selected Video Layout · Pixels", ja: "選択映像の配置 · ピクセル" },
  "왼쪽 위 기준": { en: "Top-left Origin", ja: "左上基準" },
  "미리보기 영상의 테두리와 손잡이를 드래그하거나 값을 직접 입력하세요. 방향키는 1px, Shift+방향키는 10px입니다.": { en: "Drag the preview border and handles, or enter values directly. Arrow keys move by 1 px; Shift+arrow keys move by 10 px.", ja: "プレビューの枠とハンドルをドラッグするか、値を直接入力してください。矢印キーで1px、Shift+矢印キーで10px移動します。" },
  "원본 화면 비율 유지": { en: "Lock Source Aspect Ratio", ja: "元映像のアスペクト比を維持" },
  "미세한 검은 틈 보정": { en: "Fix Thin Black Gaps", ja: "細い黒い隙間を補正" },
  "선택 영상의 화면 가장자리를 검사합니다.": { en: "Inspect the edges of the selected video.", ja: "選択映像の画面端を検査します。" },
  "← 왼쪽": { en: "← Left", ja: "← 左" },
  "오른쪽 →": { en: "Right →", ja: "右 →" },
  "↑ 위": { en: "↑ Top", ja: "↑ 上" },
  "아래 ↓": { en: "Bottom ↓", ja: "下 ↓" },
  "감지된 틈 모두 보정": { en: "Fix All Detected Gaps", ja: "検出した隙間をすべて補正" },
  "1–24px의 작은 틈만 보정하며, 크게 비워 둔 의도적 여백과 원본 크롭은 건드리지 않습니다.": { en: "Only gaps of 1–24 px are fixed. Intentional large margins and source crops are left unchanged.", ja: "1〜24pxの小さな隙間だけを補正し、意図的な大きな余白や元映像のクロップは変更しません。" },
  "기존 프로젝트 화면 맞춤": { en: "Legacy Project Framing", ja: "旧プロジェクトのフレーミング" },
  "이전 방식으로 저장된 쇼츠의 맞춤·초점 값을 조정합니다.": { en: "Adjust framing and focal-point values for Shorts saved in the legacy format.", ja: "旧形式で保存されたショート動画のフレーミングと焦点を調整します。" },
  "영상 맞춤": { en: "Framing", ja: "フレーミング" },
  "화면 채움 · 추천": { en: "Fill Frame · Recommended", ja: "画面を埋める · 推奨" },
  "전체 보이기 · 검은 여백": { en: "Fit Entire Video · Letterbox", ja: "全体を表示 · 黒い余白" },
  "원본 자르기 확대": { en: "Crop & Zoom Source", ja: "元映像をクロップして拡大" },
  "자르기 가로 초점": { en: "Horizontal Crop Focus", ja: "クロップの横方向焦点" },
  "자르기 세로 초점": { en: "Vertical Crop Focus", ja: "クロップの縦方向焦点" },
  "쇼츠 화면 안 영상 크기": { en: "Video Scale on Shorts Canvas", ja: "ショート画面内の映像サイズ" },
  "쇼츠 화면 가로 위치": { en: "Horizontal Position on Shorts Canvas", ja: "ショート画面の横位置" },
  "쇼츠 화면 세로 위치": { en: "Vertical Position on Shorts Canvas", ja: "ショート画面の縦位置" },
  "빠른 배치": { en: "Quick Position", ja: "クイック配置" },
  "플랫폼 UI 안전 영역": { en: "Platform UI Safe Area", ja: "プラットフォームUIのセーフエリア" },
  "제목·버튼·캡션이 가려질 수 있는 영역을 미리보기 위에 표시합니다.": { en: "Show areas where titles, buttons, or captions may be obscured on the preview.", ja: "タイトル・ボタン・キャプションが隠れる可能性のある領域をプレビュー上に表示します。" },
  "선택 영상 배치 초기화": { en: "Reset Selected Video Layout", ja: "選択映像の配置をリセット" },
  "모든 영상에 배치 복사": { en: "Apply Layout to All Videos", ja: "配置をすべての映像に適用" },
  "영상 · 이미지 · 음성 · 자막": { en: "Video · Images · Audio · Captions", ja: "映像 · 画像 · オーディオ · 字幕" },
  "영상 · 이미지 · 자막 · 음성 설정": { en: "Video · Images · Captions · Audio", ja: "映像 · 画像 · 字幕 · オーディオ設定" },
  "컷·원본 관리": { en: "Clips & Source", ja: "クリップ・素材管理" },
  "접기": { en: "Collapse", ja: "折りたたむ" },
  "선택 해제": { en: "Clear Selection", ja: "選択を解除" },
  "구간 삭제": { en: "Ripple Delete", ja: "リップル削除" },
  "앞뒤 빈 구간 제거": { en: "Trim Empty Head & Tail", ja: "前後の空白をトリミング" },
  "+ 이미지 붙여넣기": { en: "+ Paste Image", ja: "+ 画像を貼り付け" },
  "+ 현재 위치 음성 설정": { en: "+ Audio at Playhead", ja: "+ 再生ヘッドにオーディオ設定" },
  "+ 현재 위치에 자막": { en: "+ Caption at Playhead", ja: "+ 再生ヘッドに字幕" },
  "전체 보기": { en: "Fit Timeline", ja: "タイムライン全体表示" },
  "자석": { en: "Snapping", ja: "スナップ" },
  "음성 설정": { en: "Audio Settings", ja: "オーディオ設定" },
  "구형 원본 음성 호환": { en: "Legacy Source Audio Compatibility", ja: "旧形式の元音声との互換" },
  "이 위치를 삭제 시작점으로": { en: "Set Ripple Delete In Here", ja: "ここをリップル削除のイン点に設定" },
  "이 위치를 삭제 끝점으로": { en: "Set Ripple Delete Out Here", ja: "ここをリップル削除のアウト点に設定" },
  "선택 구간 삭제": { en: "Ripple Delete Selection", ja: "選択範囲をリップル削除" },
  "이 위치에 자막 추가": { en: "Add Caption Here", ja: "ここに字幕を追加" },
  "이 위치에 이미지 붙여넣기": { en: "Paste Image Here", ja: "ここに画像を貼り付け" },
  "이 위치에 이미지 파일 선택…": { en: "Choose Image File Here…", ja: "ここに画像ファイルを選択…" },
  "이 위치에 음성 설정 추가": { en: "Add Audio Settings Here", ja: "ここにオーディオ設定を追加" },
  "이 음성 설정 삭제": { en: "Delete These Audio Settings", ja: "このオーディオ設定を削除" },
  "자막 레인 하나 더": { en: "Add Caption Track", ja: "字幕トラックを追加" },
  "자막 문구를 제외한 설정만 한눈에 비교합니다. 위치·크기·색상·검은 상자가 주변 자막과 다른지 검수해 보세요.": { en: "Compare settings without revealing caption text. Review whether position, size, color, or black-box styling differs from neighboring captions.", ja: "字幕テキストを除いた設定を一覧で比較します。位置・サイズ・色・黒いボックスが前後の字幕と異なっていないか確認してください。" },
  "자막 속성을 시간순으로 준비합니다.": { en: "Preparing caption properties in timeline order.", ja: "字幕プロパティを時系列で準備しています。" },
  "위치·크기·글자색·검은 상자의 공통 설정과 개별 설정을 비교합니다.": { en: "Compare shared and individual settings for position, size, text color, and black box.", ja: "位置・サイズ・文字色・黒いボックスの共通設定と個別設定を比較します。" },
  "이 비교표는 편집 화면에서만 보이며 영상 출력에는 포함되지 않습니다.": { en: "This comparison table is visible only in the editor and is not included in the exported video.", ja: "この比較表は編集画面だけに表示され、書き出した動画には含まれません。" },
  "자막 문구를 제외한 자막별 스타일 설정 비교표": { en: "Caption style comparison table excluding caption text", ja: "字幕テキストを除く字幕別スタイル設定の比較表" },
  "컷": { en: "Clip", ja: "クリップ" },
  "시작 시각": { en: "Start Time", ja: "開始時刻" },
  "레인": { en: "Track", ja: "トラック" },
  "위치 X/Y": { en: "Position X/Y", ja: "位置 X/Y" },
  "설정 크기": { en: "Set Size", ja: "設定サイズ" },
  "글자색": { en: "Text Color", ja: "文字色" },
  "검은 상자": { en: "Black Box", ja: "黒いボックス" },
  "설정 묶음": { en: "Setting Group", ja: "設定グループ" },
  "비교할 자막이 없습니다.": { en: "There are no captions to compare.", ja: "比較する字幕がありません。" },
  "출력 중인 자막의 행 번호를 누르면 해당 자막 편집기로 이동합니다.": { en: "Select the row number of an active caption to open it in the caption inspector.", ja: "表示中の字幕の行番号を選択すると、その字幕の編集パネルへ移動します。" },
  "강조된 차이는 확인할 후보이며 확정된 오류가 아닙니다.": { en: "Highlighted differences are review candidates, not confirmed errors.", ja: "強調された差分は確認候補であり、確定したエラーではありません。" },
  "반자동 노래 자막 편집 팁": { en: "Semi-automated Lyric Caption Workflow", ja: "半自動の歌詞字幕編集ガイド" },
  "노래 가사를 넣을 때, 가사 타이밍을 자동으로 맞춰주는 프롬프트입니다": { en: "A prompt for automatically aligning lyric timing", ja: "歌詞のタイミングを自動で合わせるためのプロンプトです" },
  "사용 방법": { en: "How to Use", ja: "使い方" },
  "컷 순서·길이·크롭·영상/음성 구도를 사람이 먼저 완성한 뒤, 그 편집의 로컬 오디오와 줄 ID가 붙은 가사를 준비합니다.": { en: "First complete the clip order, duration, crop, and video/audio composition manually. Then prepare the edit's local audio and lyrics with line IDs.", ja: "まずクリップ順・長さ・クロップ・映像／音声の構成を手作業で仕上げ、その編集のローカル音声と行ID付きの歌詞を用意します。" },
  "아래 SKILL.md를 AI Agent에 넣고, ASR·강제정렬·VAD 같은 로컬 분석 근거와 함께 실행합니다.": { en: "Give the SKILL.md below to an AI agent and run it with local analysis evidence such as ASR, forced alignment, and VAD.", ja: "下のSKILL.mdをAIエージェントに渡し、ASR・強制アライメント・VADなどのローカル解析結果とともに実行します。" },
  "에이전트가 자막 문구·싱크·레인·줄바꿈·위치를 완성편집으로 한 번에 넣으면,": { en: "After the agent applies caption text, timing, tracks, line breaks, and positions as a finished edit,", ja: "エージェントが字幕テキスト・同期・トラック・改行・位置を完成版として一括反映したら、" },
  "추정 확정·검수 우선순위 높음": { en: "Estimated, confirmed · High review priority", ja: "推定確定・確認優先度：高" },
  "큐부터 사람이 사후 검수합니다.": { en: "review those cues manually first.", ja: "のキューから人が事後確認します。" },
  "이 버튼은 사용 스킬만 보여 줍니다. 현재 영상·자막을 외부 모델로 보내거나 사용 기록을 저장하지 않으며, 에이전트도 영상 컷과 구도를 바꾸지 않습니다.": { en: "This button only displays the skill instructions. It does not send the current video or captions to an external model or store usage history, and the agent does not change video cuts or composition.", ja: "このボタンは使用するスキルだけを表示します。現在の映像や字幕を外部モデルへ送信したり、利用履歴を保存したりすることはなく、エージェントも映像のカットや構図を変更しません。" },
  "SKILL.md 복사": { en: "Copy SKILL.md", ja: "SKILL.mdをコピー" },
  "저장·복구본 최대 5개": { en: "Up to 5 Versions & Recovery Copies", ja: "保存版・復元は最大5件" },
  "직접 저장한 버전과 편집 중 복구본을 합쳐 최근 5개까지 이 기기에 둡니다.": { en: "This device keeps the five most recent manual versions and in-progress recovery copies combined.", ja: "手動保存版と編集中の復元データを合わせ、最新5件までこのデバイスに保存します。" },
  "탭 종료 뒤에는 ‘지금 저장’으로 만든 버전만 남습니다.": { en: "After this tab closes, only versions created with Save Version remain.", ja: "タブを閉じた後は「バージョンを保存」で作成した版だけが残ります。" },
  "편집 중·불러오기 전 복구본은 자동으로 정리됩니다.": { en: "In-progress and pre-restore recovery copies are removed automatically.", ja: "編集中および読み込み前の復元データは自動的に整理されます。" },
  "이 사이트의 기기 내 데이터를 지우면 저장본도 함께 삭제됩니다.": { en: "Clearing this site's data from your device also deletes saved versions.", ja: "このサイトのデバイス内データを消去すると、保存版も削除されます。" },
  "아직 직접 저장한 버전이나 편집 중 복구본이 없습니다.": { en: "There are no saved versions or in-progress recovery copies yet.", ja: "手動保存版や編集中の復元データはまだありません。" },
  "선택한 버전을 불러오기 전에 현재 상태의 편집 중 복구본을 만듭니다. 이 복구본도 탭 종료 시 폐기됩니다.": { en: "An in-progress recovery copy of the current state is created before the selected version loads. This recovery copy is also discarded when the tab closes.", ja: "選択した版を読み込む前に、現在の状態を編集中の復元データとして作成します。この復元データもタブを閉じると破棄されます。" },
  "시작 화면에서 직접 저장본을 다시 열 때는 이번 사용의 사용자 진술을 다시 입력해야 합니다.": { en: "When reopening a manual version from the start screen, you must enter the required user declaration again for this session.", ja: "スタート画面から手動保存版を開き直す場合は、今回の利用に関するユーザー申告を再入力する必要があります。" },
  "내보낸 편집 복원 파일 열기": { en: "Open Exported Edit Recovery File", ja: "書き出した編集復元ファイルを開く" },
  "선택한 버전 불러오기": { en: "Load Selected Version", ja: "選択した版を読み込む" },
  "영상과 다시 편집할 때 사용할 복원 파일을 함께 저장합니다. 원본 영상 자체는 복원 파일에 포함하지 않습니다.": { en: "Saves the video together with a recovery file for future editing. The source video itself is not included in the recovery file.", ja: "動画と、再編集に使用する復元ファイルを一緒に保存します。元の動画自体は復元ファイルに含まれません。" },
  "출력 영상 제목": { en: "Export Title", ja: "書き出し動画のタイトル" },
  "내보낼 파일 이름을 먼저 정해 주세요.": { en: "Choose a filename before exporting.", ja: "書き出すファイル名を先に指定してください。" },
  "쇼츠 가장자리에 작은 검은 틈이 보일 수 있습니다.": { en: "Thin black gaps may appear along the edges of the Shorts frame.", ja: "ショート動画の端に細い黒い隙間が見える場合があります。" },
  "밀대 도구로 확인할 수 있습니다.": { en: "Use the gap-fix tool to inspect them.", ja: "隙間補正ツールで確認できます。" },
  "영상·편집 복원 파일·자막 파일이 제대로 저장됐는지 확인한 뒤, 이 작업에 사용한 임시 영상과 기기 내 편집 데이터를 지울지 별도로 묻습니다.": { en: "After you confirm that the video, edit recovery file, and caption file were saved correctly, you will be asked separately whether to remove this project's temporary media and local edit data.", ja: "動画・編集復元ファイル・字幕ファイルが正しく保存されたことを確認した後、この作業で使用した一時映像とデバイス内の編集データを削除するか別途確認します。" },
  "저장 위치 선택하고 내보내기": { en: "Choose Destination & Export", ja: "保存先を選んで書き出す" },
  "내보내기를 검증했습니다": { en: "Export Verified", ja: "書き出しを確認しました" },
  "영상과 복원 파일이 선택한 폴더에 정상 저장되었습니다.": { en: "The video and recovery file were saved successfully to the selected folder.", ja: "動画と復元ファイルが選択したフォルダーに正常に保存されました。" },
  "현재 편집을 완료하고 이 작업의 임시 자료를 지울까요?": { en: "Finish this edit and remove its temporary data?", ja: "現在の編集を完了し、この作業の一時データを削除しますか？" },
  "이 작업용으로 받은 VOD 구간·쇼츠 미리보기·저장본·이미지·파일 연결만 지웁니다. 다른 편집 작업과 사용자가 직접 선택한 원본 영상 파일은 삭제하지 않습니다.": { en: "Only downloaded VOD segments, Shorts previews, saved versions, images, and file connections for this project are removed. Other editing projects and source video files you selected directly are not deleted.", ja: "この作業用に取得したVOD区間・ショート動画プレビュー・保存版・画像・ファイル接続だけを削除します。他の編集作業や、ユーザーが直接選択した元動画ファイルは削除しません。" },
  "삭제하면 이 작업은 종료됩니다. 다시 편집하려면 방금 저장한 편집 복원 파일과 원본 VOD 또는 원본 파일이 필요합니다. 다른 탭이 같은 작업을 사용 중이거나 안전하게 지울 범위를 확인하지 못하면 삭제하지 않습니다.": { en: "Deleting this data ends the project. To edit it again, you will need the edit recovery file you just saved and the source VOD or source file. Nothing is deleted if another tab is using the project or the safe deletion scope cannot be verified.", ja: "削除するとこの作業は終了します。再編集には、保存した編集復元ファイルと元のVODまたは元ファイルが必要です。別のタブが同じ作業を使用中の場合や、安全に削除できる範囲を確認できない場合は削除しません。" },
  "유지하고 계속 편집": { en: "Keep Data & Continue Editing", ja: "保持して編集を続ける" },
  "작업 완료·임시 자료 삭제": { en: "Finish & Remove Temporary Data", ja: "完了して一時データを削除" },
  "현재 편집 작업을 정리했습니다": { en: "Editing Project Cleaned Up", ja: "編集作業を整理しました" },
  "내보낸 영상과 편집 복원 파일은 그대로 보존되고, 이 작업이 사용하던 기기 내 임시 자료만 삭제했습니다.": { en: "The exported video and edit recovery file were preserved. Only temporary data used by this project was removed from this device.", ja: "書き出した動画と編集復元ファイルはそのまま保持され、この作業が使用していたデバイス内の一時データだけを削除しました。" },
  "이 탭에서는 더 이상 자동저장하거나 편집하지 않습니다.": { en: "This tab will no longer autosave or allow editing.", ja: "このタブでは、これ以降自動保存や編集を行いません。" },
  "다시 작업하려면 원본 페이지에서 새 편집을 시작한 뒤 ‘내보낸 편집 복원 파일 열기’를 사용하세요.": { en: "To resume editing, start a new edit from the source page and choose Open Exported Edit Recovery File.", ja: "再編集するには、元のページから新しい編集を開始し、「書き出した編集復元ファイルを開く」を使用してください。" },
  "작업을 끝낼까요?": { en: "Finish editing?", ja: "編集を終了しますか？" },
  "이번 편집에서 바꾼 내용을 이 기기에 남길지 선택해 주세요.": { en: "Choose whether to keep the changes from this editing session on this device.", ja: "今回の編集で変更した内容をこのデバイスに残すか選択してください。" },
  "이 기기에 저장하고 나가기": { en: "Save to This Device & Exit", ja: "このデバイスに保存して終了" },
  "현재 상태를 다음에 이어서 열 수 있는 편집으로 확정합니다.": { en: "Keeps the current state as an edit you can resume later.", ja: "現在の状態を、次回続きから開ける編集として保存します。" },
  "저장하지 않고 나가기": { en: "Exit Without Saving", ja: "保存せず終了" },
  "이번에 편집기를 연 뒤 생긴 변경을 버리고, 열기 전 상태로 되돌립니다. 직접 만든 저장본은 남깁니다.": { en: "Discards changes made since opening the editor and restores the previous state. Manually saved versions are kept.", ja: "エディターを開いてからの変更を破棄し、開く前の状態に戻します。手動で作成した保存版は残ります。" },
  "탭을 그냥 닫으면 이번 변경은 저장되지 않습니다. 다음 시작 화면에서 직접 만든 저장본은 남기고, 나머지는 열기 전 상태로 자동 정리합니다.": { en: "Closing the tab directly will not save these changes. The next start screen keeps manual versions and automatically restores everything else to its pre-open state.", ja: "タブをそのまま閉じると今回の変更は保存されません。次のスタート画面では手動保存版を残し、それ以外は開く前の状態に自動で戻します。" },
  "영상을 준비하고 있어요": { en: "Preparing Media", ja: "映像を準備しています" },
  "선택한 구간의 편집 영상을 이 기기에 준비합니다.": { en: "Preparing media for the selected clips on this device.", ja: "選択クリップの編集用メディアをこのデバイスに準備しています。" },
  "웹 편집을 위한 로컬 영상 준비": { en: "Prepare Local Media for Web Editing", ja: "Web編集用のローカル映像を準備" },
  "영상 준비 도우미만 연결하면 바로 이어집니다": { en: "Connect the media helper to continue", ja: "映像準備ヘルパーを接続すると続行できます" },
  "편집은 계속 이 웹사이트에서 합니다. 도우미는 선택한 영상 구간만 이 PC에 준비하며 별도 작업 창을 열지 않습니다.": { en: "Editing stays on this website. The helper only prepares selected video segments on this PC and does not open a separate workspace.", ja: "編集は引き続きこのWebサイトで行います。ヘルパーは選択した映像区間だけをこのPCに準備し、別の作業画面は開きません。" },
  "내 PC용 도우미 받기": { en: "Get the Helper for This PC", ja: "このPC用ヘルパーを入手" },
  "운영체제에 맞는 설치 파일을 고릅니다.": { en: "Choose the installer for your operating system.", ja: "お使いのOSに合ったインストーラーを選びます。" },
  "다운로드 후 설치·실행": { en: "Download, Install & Run", ja: "ダウンロード・インストール・起動" },
  "설치 파일을 실행하고 도우미를 한 번 시작합니다.": { en: "Run the installer, then start the helper once.", ja: "インストーラーを実行し、ヘルパーを一度起動します。" },
  "이 화면에서 연결 확인": { en: "Confirm Connection Here", ja: "この画面で接続を確認" },
  "도우미 실행을 확인한 뒤 이 브라우저에서 원래 편집을 이어갑니다.": { en: "After confirming the helper is running, continue the original edit in this browser.", ja: "ヘルパーの起動を確認したら、このブラウザーで元の編集を続けます。" },
  "현재 공개 테스트는 Debian/Ubuntu·Arch Linux x64만 지원합니다.": { en: "The current public test supports Debian/Ubuntu and Arch Linux x64 only.", ja: "現在の公開テストはDebian/UbuntuおよびArch Linux x64のみ対応しています。" },
  "다운로드를 누르면 이 화면에 다음 행동을 계속 안내합니다. 실제 파일 진행률은 브라우저의 다운로드 표시에서 확인할 수 있습니다.": { en: "After you start the download, this screen continues to guide you through the next steps. Check the browser's download indicator for actual file progress.", ja: "ダウンロードを開始すると、この画面で次の手順を引き続き案内します。実際の進捗はブラウザーのダウンロード表示で確認できます。" },
  "도우미 소스·라이선스 안내": { en: "Helper Source & License", ja: "ヘルパーのソース・ライセンス" },
  "내 파일로 계속하기": { en: "Continue with a Local File", ja: "ローカルファイルで続行" },
  "연결 기억 지우기": { en: "Forget Connection", ja: "接続情報を消去" },
  "설치 후 연결 확인": { en: "Confirm Connection After Installation", ja: "インストール後に接続を確認" },
  "Arch Linux용 도우미 (.pkg.tar.zst)": { en: "Helper for Arch Linux (.pkg.tar.zst)", ja: "Arch Linux用ヘルパー (.pkg.tar.zst)" },
  "내 PC용 도우미 다운로드": { en: "Download Helper for This PC", ja: "このPC用ヘルパーをダウンロード" },
  "받은 영상 조각과 편집 데이터는 이 기기에서 처리되며 Kirinuki 운영 서버의 프로젝트 데이터베이스로 보내지지 않습니다. 광고와 원본 미리보기 제공자는 접속정보 등을 처리할 수 있습니다.": { en: "Downloaded video segments and edit data are processed on this device and are not sent to Kirinuki's project database. Advertising and source-preview providers may process connection information and related data.", ja: "取得した映像断片と編集データはこのデバイスで処理され、Kirinuki運用サーバーのプロジェクトデータベースには送信されません。広告および元映像プレビューの提供者は、接続情報などを処理する場合があります。" },
  "개인정보 처리 안내": { en: "Privacy Notice", ja: "プライバシーについて" },
  "앞 30초": { en: "Previous 30 sec", ja: "前の30秒" },
  "뒤 30초": { en: "Next 30 sec", ja: "次の30秒" },
  "키리누키 프로젝트": { en: "Kirinuki Project", ja: "Kirinukiプロジェクト" },
  "Kirinuki 상표": { en: "Kirinuki Brand", ja: "Kirinukiブランド" },
  "영상 준비와 내보내기": { en: "Media Preparation and Export", ja: "メディア準備と書き出し" },
  "본편 편집으로 돌아가기": { en: "Return to Main Edit", ja: "本編編集に戻る" },
  "편집 실행 취소와 저장": { en: "Undo, Redo, and Save", ja: "取り消し・やり直し・保存" },
  "실행 취소 (Ctrl+Z)": { en: "Undo (Ctrl+Z)", ja: "元に戻す (Ctrl+Z)" },
  "실행 취소": { en: "Undo", ja: "元に戻す" },
  "다시 실행 (Ctrl+Shift+Z)": { en: "Redo (Ctrl+Shift+Z)", ja: "やり直す (Ctrl+Shift+Z)" },
  "다시 실행": { en: "Redo", ja: "やり直す" },
  "이 기기 저장": { en: "Save on This Device", ja: "このデバイスに保存" },
  "현재 편집 상태를 이 기기에 저장": { en: "Save the current edit state on this device", ja: "現在の編集状態をこのデバイスに保存" },
  "지금 이 기기에 저장": { en: "Save a version on this device now", ja: "現在の状態をこのデバイスに保存" },
  "저장·복구본 목록": { en: "Versions & Recovery List", ja: "保存版・復元一覧" },
  "저장·복구본 목록 열기": { en: "Open Versions & Recovery", ja: "保存版・復元一覧を開く" },
  "현재 작업을 저장하거나 폐기하고 시작 화면으로 돌아가기": { en: "Save or discard the current project and return to the start screen", ja: "現在の作業を保存または破棄してスタート画面に戻る" },
  "컷·원본 관리 닫기": { en: "Close Clips & Source", ja: "クリップ・素材管理を閉じる" },
  "체크한 컷 순서 이동": { en: "Reorder Selected Clips", ja: "選択クリップの順序を変更" },
  "체크한 컷을 한 단계 위로 이동": { en: "Move selected clips up one position", ja: "選択クリップを1つ上へ移動" },
  "체크한 컷을 한 단계 위로 이동 (Alt+↑)": { en: "Move selected clips up one position (Alt+↑)", ja: "選択クリップを1つ上へ移動 (Alt+↑)" },
  "체크한 컷을 한 단계 아래로 이동": { en: "Move selected clips down one position", ja: "選択クリップを1つ下へ移動" },
  "체크한 컷을 한 단계 아래로 이동 (Alt+↓)": { en: "Move selected clips down one position (Alt+↓)", ja: "選択クリップを1つ下へ移動 (Alt+↓)" },
  "컷 체크 전체 해제": { en: "Clear all clip selections", ja: "クリップの選択をすべて解除" },
  "미리보기 도구": { en: "Preview Tools", ja: "プレビューツール" },
  "현재 본편에서 시간과 화면 영역을 골라 쇼츠에 영상 추가": { en: "Choose a time range and frame area from the main edit to add video to Shorts", ja: "本編から時間範囲と画面領域を選び、ショート動画に映像を追加" },
  "원본 영상 화면 영역 선택": { en: "Select Source Video Area", ja: "元映像の画面領域を選択" },
  "쇼츠로 가져올 원본 영상 영역": { en: "Source video area to use in Shorts", ja: "ショート動画に取り込む元映像の領域" },
  "선택 영역 이동. 방향키 1픽셀, Shift와 방향키 10픽셀": { en: "Move selection. Arrow keys: 1 px; Shift+arrow keys: 10 px", ja: "選択領域を移動。矢印キー：1px、Shift+矢印キー：10px" },
  "선택 영역 왼쪽 위 크기 조절": { en: "Resize selection from top left", ja: "選択領域を左上からリサイズ" },
  "선택 영역 위쪽 크기 조절": { en: "Resize selection from top", ja: "選択領域を上からリサイズ" },
  "선택 영역 오른쪽 위 크기 조절": { en: "Resize selection from top right", ja: "選択領域を右上からリサイズ" },
  "선택 영역 오른쪽 크기 조절": { en: "Resize selection from right", ja: "選択領域を右からリサイズ" },
  "선택 영역 오른쪽 아래 크기 조절": { en: "Resize selection from bottom right", ja: "選択領域を右下からリサイズ" },
  "선택 영역 아래쪽 크기 조절": { en: "Resize selection from bottom", ja: "選択領域を下からリサイズ" },
  "선택 영역 왼쪽 아래 크기 조절": { en: "Resize selection from bottom left", ja: "選択領域を左下からリサイズ" },
  "선택 영역 왼쪽 크기 조절": { en: "Resize selection from left", ja: "選択領域を左からリサイズ" },
  "쇼츠 소스 설정 접기": { en: "Collapse Shorts Source Settings", ja: "ショート動画素材の設定を折りたたむ" },
  "설정 접기": { en: "Collapse Settings", ja: "設定を折りたたむ" },
  "쇼츠 소스 만들기 취소": { en: "Cancel Creating Shorts Source", ja: "ショート動画素材の作成をキャンセル" },
  "컷 기준 구간 빠른 선택": { en: "Quick Clip-based Range Selection", ja: "クリップ基準のクイック範囲選択" },
  "쇼츠 소스 시작 시각 조절": { en: "Adjust Shorts Source In Point", ja: "ショート動画素材のイン点を調整" },
  "쇼츠 소스 끝 시각 조절": { en: "Adjust Shorts Source Out Point", ja: "ショート動画素材のアウト点を調整" },
  "원본 화면 비율": { en: "Source Aspect Ratio", ja: "元映像のアスペクト比" },
  "쇼츠 전용 9대16 합성 미리보기": { en: "9:16 Shorts Composition Preview", ja: "ショート動画用9:16合成プレビュー" },
  "1080×1920 쇼츠 화면 영상 배치": { en: "Position video on the 1080×1920 Shorts canvas", ja: "1080×1920ショート画面に映像を配置" },
  "쇼츠 영상": { en: "Shorts Video", ja: "ショート動画" },
  "선택 영상의 쇼츠 화면 배치 영역": { en: "Selected video's layout area on the Shorts canvas", ja: "選択映像のショート画面配置領域" },
  "선택 영상 이동. 방향키 1픽셀, Shift와 방향키 10픽셀": { en: "Move selected video. Arrow keys: 1 px; Shift+arrow keys: 10 px", ja: "選択映像を移動。矢印キー：1px、Shift+矢印キー：10px" },
  "영상 왼쪽 위 크기 조절": { en: "Resize video from top left", ja: "映像を左上からリサイズ" },
  "영상 위쪽 크기 조절": { en: "Resize video from top", ja: "映像を上からリサイズ" },
  "영상 오른쪽 위 크기 조절": { en: "Resize video from top right", ja: "映像を右上からリサイズ" },
  "영상 오른쪽 크기 조절": { en: "Resize video from right", ja: "映像を右からリサイズ" },
  "영상 오른쪽 아래 크기 조절": { en: "Resize video from bottom right", ja: "映像を右下からリサイズ" },
  "영상 아래쪽 크기 조절": { en: "Resize video from bottom", ja: "映像を下からリサイズ" },
  "영상 왼쪽 아래 크기 조절": { en: "Resize video from bottom left", ja: "映像を左下からリサイズ" },
  "영상 왼쪽 크기 조절": { en: "Resize video from left", ja: "映像を左からリサイズ" },
  "이전 구간": { en: "Previous Clip", ja: "前のクリップ" },
  "이전 구간으로 이동 (단축키 ,)": { en: "Go to previous clip (shortcut: ,)", ja: "前のクリップへ移動 (ショートカット: ,)" },
  "재생": { en: "Play", ja: "再生" },
  "미리보기 재생 또는 일시정지 (단축키 Space)": { en: "Play or pause preview (shortcut: Space)", ja: "プレビューを再生または一時停止 (ショートカット: Space)" },
  "다음 구간": { en: "Next Clip", ja: "次のクリップ" },
  "다음 구간으로 이동 (단축키 .)": { en: "Go to next clip (shortcut: .)", ja: "次のクリップへ移動 (ショートカット: .)" },
  "음소거": { en: "Mute", ja: "ミュート" },
  "볼륨": { en: "Volume", ja: "音量" },
  "속성 편집 종류": { en: "Property Inspector", ja: "プロパティ編集" },
  "자막 위치 자동 배치": { en: "Auto-place Captions", ja: "字幕位置を自動配置" },
  "자막 편집 보기": { en: "Caption Inspector View", ja: "字幕編集ビュー" },
  "자막 내용을 입력하세요": { en: "Enter caption text", ja: "字幕テキストを入力" },
  "선택 자막 검은 사각 배경": { en: "Black box for selected caption", ja: "選択字幕の黒いボックス" },
  "같은 자막 레인의 좌우 자막 이동": { en: "Navigate captions on the same track", ja: "同じ字幕トラック内を移動" },
  "같은 자막 레인의 왼쪽 자막으로 이동": { en: "Go to previous caption on the same track", ja: "同じ字幕トラックの前の字幕へ移動" },
  "같은 자막 레인의 오른쪽 자막으로 이동": { en: "Go to next caption on the same track", ja: "同じ字幕トラックの次の字幕へ移動" },
  "선택 자막 색상 고르기": { en: "Choose selected caption color", ja: "選択字幕の色を選択" },
  "기본 흰색과 최근 자막 색상": { en: "Default white and recent caption colors", ja: "デフォルトの白と最近の字幕色" },
  "쇼츠 작업 관리": { en: "Manage Shorts Projects", ja: "ショート動画プロジェクトを管理" },
  "쇼츠 화면의 영상 목록": { en: "Videos on the Shorts canvas", ja: "ショート画面の映像一覧" },
  "선택 영상 설정": { en: "Selected Video Settings", ja: "選択映像の設定" },
  "선택 영상 표시": { en: "Show selected video", ja: "選択映像を表示" },
  "선택 영상의 미세한 검은 틈 보정": { en: "Fix thin black gaps around selected video", ja: "選択映像の細い黒い隙間を補正" },
  "왼쪽 위": { en: "Top Left", ja: "左上" },
  "가운데 위": { en: "Top Center", ja: "上中央" },
  "오른쪽 위": { en: "Top Right", ja: "右上" },
  "왼쪽 가운데": { en: "Center Left", ja: "左中央" },
  "정가운데": { en: "Center", ja: "中央" },
  "오른쪽 가운데": { en: "Center Right", ja: "右中央" },
  "왼쪽 아래": { en: "Bottom Left", ja: "左下" },
  "가운데 아래": { en: "Bottom Center", ja: "下中央" },
  "오른쪽 아래": { en: "Bottom Right", ja: "右下" },
  "쇼츠 화면 맞춤 작업": { en: "Shorts Canvas Framing", ja: "ショート画面のフレーミング" },
  "타임라인 접기": { en: "Collapse Timeline", ja: "タイムラインを折りたたむ" },
  "영상 구간 삭제": { en: "Ripple Delete Video Range", ja: "映像範囲をリップル削除" },
  "현재 재생 위치를 삭제 시작점으로 지정 (I)": { en: "Mark the current playhead as the ripple-delete In point (I)", ja: "現在の再生ヘッドをリップル削除のイン点に設定 (I)" },
  "현재 재생 위치를 삭제 끝점으로 지정 (O)": { en: "Mark the current playhead as the ripple-delete Out point (O)", ja: "現在の再生ヘッドをリップル削除のアウト点に設定 (O)" },
  "삭제 구간 선택 해제 (Esc)": { en: "Clear ripple-delete range (Esc)", ja: "リップル削除範囲を解除 (Esc)" },
  "선택한 영상 구간 삭제 (Delete)": { en: "Ripple delete selected video range (Delete)", ja: "選択した映像範囲をリップル削除 (Delete)" },
  "영상·사진·자막·음성 중 가장 이른 시작과 가장 늦은 끝에 쇼츠 길이를 맞춥니다": { en: "Fit the Shorts duration to the earliest start and latest end across video, images, captions, and audio", ja: "映像・画像・字幕・オーディオの最も早い開始点と最も遅い終了点にショート動画の長さを合わせます" },
  "타임라인 자석 켜짐 · 드래그 중 Alt로 잠시 해제": { en: "Timeline snapping on · Hold Alt while dragging to bypass", ja: "タイムラインのスナップ：オン · ドラッグ中にAltで一時解除" },
  "타임라인 확대": { en: "Timeline Zoom", ja: "タイムラインのズーム" },
  "영상 라인 추가": { en: "Add Video Track", ja: "映像トラックを追加" },
  "자막 레인 추가": { en: "Add Caption Track", ja: "字幕トラックを追加" },
  "이미지 트랙": { en: "Image Track", ja: "画像トラック" },
  "구형 쇼츠 원본 음성 호환 트랙": { en: "Legacy Shorts Source Audio Compatibility Track", ja: "旧ショート動画の元音声互換トラック" },
  "삭제 구간 시작 시각": { en: "Ripple-delete range start time", ja: "リップル削除範囲の開始時刻" },
  "삭제 구간 끝 시각": { en: "Ripple-delete range end time", ja: "リップル削除範囲の終了時刻" },
  "편집 재생 시각": { en: "Edit Playhead Time", ja: "編集再生時刻" },
  "타임라인 메뉴": { en: "Timeline Menu", ja: "タイムラインメニュー" },
  "자막 스타일 비교 닫기": { en: "Close Caption Style Comparison", ja: "字幕スタイル比較を閉じる" },
  "닫기": { en: "Close", ja: "閉じる" },
  "자막 속성 비교표 스크롤 영역": { en: "Scrollable Caption Property Comparison Table", ja: "字幕プロパティ比較表のスクロール領域" },
  "노래 자막 싱크 팁 닫기": { en: "Close Lyric Caption Timing Guide", ja: "歌詞字幕同期ガイドを閉じる" },
  "노래 자막 싱크 사용법과 SKILL.md": { en: "Lyric Caption Timing Workflow and SKILL.md", ja: "歌詞字幕同期の使い方とSKILL.md" },
  "SKILL.md 원문": { en: "Full SKILL.md Text", ja: "SKILL.md全文" },
  "저장·복구본 목록 닫기": { en: "Close Versions & Recovery", ja: "保存版・復元一覧を閉じる" },
  "불러올 저장·복구본": { en: "Version or Recovery Copy to Load", ja: "読み込む保存版・復元データ" },
  "내보내기 설정 닫기": { en: "Close Export Settings", ja: "書き出し設定を閉じる" },
  "현재 작업을 유지하고 닫기": { en: "Keep Current Project and Close", ja: "現在の作業を保持して閉じる" },
  "유지하고 닫기": { en: "Keep & Close", ja: "保持して閉じる" },
  "영상 준비 도우미 연결 순서": { en: "Media Helper Connection Steps", ja: "映像準備ヘルパーの接続手順" },
  "편집 영상 범위 추가": { en: "Extend Prepared Media Range", ja: "編集用メディアの範囲を追加" },
  "본편 컷 재생 순서": { en: "Main Edit Clip Order", ja: "本編クリップの再生順" },
  "맨 처음 재생": { en: "Play First", ja: "先頭を再生" },
  "한 컷 먼저 재생": { en: "Play Previous Clip", ja: "1つ前のクリップを再生" },
  "한 컷 나중에 재생": { en: "Play Next Clip", ja: "1つ次のクリップを再生" },
  "맨 마지막 재생": { en: "Play Last", ja: "末尾を再生" },
  "화면 언어": { en: "Interface Language", ja: "表示言語" },
  "원본 영상 영역": { en: "Source Video Area", ja: "元映像の領域" },
  "확인": { en: "Review", ja: "確認" }
} as const satisfies UiCopyCatalog;
